<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>10.4 Exception Handling in Java Practical Part 3 Checked | Coder Coacher - Coaching Coders</title><meta content="10.4 Exception Handling in Java Practical Part 3 Checked - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin, machine learning, AI, ML, tech talks, angular, javascript, js, typescript"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/Telusko-Learnings/">Telusko Learnings</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>10.4 Exception Handling in Java Practical Part 3 Checked</b></h2><h5 class="post__date">2015-02-23</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/_dm5E-TUm9E" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">now so now we know that we can have
multiple type of multiple catch for one
try but what if if I have lots of
statement here right and it is not
guarantee that all these statements are
normal statement there might be some
stripping which are critical statement
which means it might throw an error and
that's why you have to handle the error
and we don't have only one class of
exception right we have multiple class
of exceptions let's say somewhere here
you got an exception that you don't know
what the exactly what exactly the
exception will be it might be electing
exception so it will be handled it might
be adding to softer autobody exception
so it might be handled but what if if we
have one more exception here which is
maybe I don't know some different type
of exception so what you can do is if
you don't know the type of exception you
can simply say at the last if it's not a
determining exception if it's not
arranged it's Auto point exceptions then
come to me I will print unknown
exception right so that you can handle
all tower exceptions so this are
specific exceptions and if you don't
know the type of exception you can
simply print exception so it's always
better to have the last catch block as
exception then you will say why don't if
you just pick this catch here why don't
you can pick this catch here and put it
here unfortunately it will give you an
error it's because let's say you got an
error on this line it will die a jump to
the first catch and first catch can
handle all the others right then what
this two exception are doing here so
always write your catch your main
exception in the as a last catch okay so
this is this is how you can have one try
with multiple catch now let's say I'm
going for the next type of example let
me remove this this start from here I
don't want array now let me remove this
part also and let me remove these two
catches because I know now I am NOT
getting a day index out of an exception
for sure because I'm not going to get at
it okay let's say
I want to take this value which is this
- from the user
I want this J value should come from the
user what it means I want to take I want
to use some type of input class and one
of the input class is bufferedreader so
if you are not going through my video
which is user input so I recommend to go
to that video you will get the idea how
to take input from user so this is a
classical as before we'll say BR equal
to new buffered reader equal to new
input stream reader what exactly this
all means I will recommend to go to that
video input stream reader and this it
will be system dot in okay let's import
the package by using ctrl shift I you
can see we got the package about now
what next now let's say since venues we
have a function in Java palace BR dot
readline now this function will fetch
the value from the user it will fetch in
a string format so we have to pass the
inputs on how to pass using integer dot
pass end and will give back it I can see
we have got EU input from user excuse me
we got the input from user and we are
storing that value in in this variable
Ecology know now the problem is there is
a chance that you are expecting an input
from user and user has given you some
wrong value with your string value and
you are trying to convert this so it
will throw an error and it's showing us
that it might throw another see this if
you go to this red bubble here it says
unreported exception I exception must be
caught it's because I exception comes at
a checked exception so your NetBeans
also know that they are your Java itself
know that it might throw an error so you
have to go here you have to write a
catch now this time this catch is will
be for
or IO exception waiting it will be for
our exception it will say it is e and
we'll print some input/output hello
okay I know that it will not try any
error was they you should know yeah and
you should write this block now and try
block so you can see we have we have
solved this salt this error and this
should be the next line because fear
when we can calculate only after the X
assignment right and the initial value
of J will set it as 0 or 1 because I
don't know the value of J once till I
get the input from user let's just run
me the run to this code which is waiting
for the input we'll say 2 and the output
is 4 right so this type of exceptions
are called as checked exceptions okay
and they can we'll continue with the
next tutorial in the next part and Dylan
do subscribe and thank you so much</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>