<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>C++ Tutorial for Beginners 37 - C++ Exception Handling (Try Throw Catch) | Coder Coacher - Coaching Coders</title><meta content="C++ Tutorial for Beginners 37 - C++ Exception Handling (Try Throw Catch) - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin, machine learning, AI, ML, tech talks, angular, javascript, js, typescript"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/ProgrammingKnowledge/">ProgrammingKnowledge</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>C++ Tutorial for Beginners 37 - C++ Exception Handling (Try Throw Catch)</b></h2><h5 class="post__date">2014-09-14</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/OtDysNsdF1s" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">hello guys in this video I'm going to
teach you what is C++ exceptions and how
you can use exception handling in C++ so
first of all what is an exception an
exception is a situation or a unwanted
situation which can arise during the
execution of your program and you can
use exception handling techniques which
is provided by C++ to handle those
exceptions for example I want the age of
some person and I am allowing the user
to enter the age and by mistake he
enters instead of any number or integer
he enters any character on any string
instead of integer as an age and this is
unacceptable and you need to handle
those situation in C++ and exception
handling in C++ provide you know
handling of those situations so for how
you can use exception handling in C++
let's see the prototype so you use try
and then give these curly braces and
then give our catch blocks so first of
all I will show you the basic syntax so
you just try your code and then catch
the exception catch and in here you can
catch exceptions so this is the basic
prototype of your exception handling in
C++ this try block in this you try your
code okay so is the name suggests you
are trying your code and if it's throws
any exception it is catched by this
block called catch and in these curly
braces
okay now for example you want to show
throw some exception intentionally so
let's stay
an example for example I want the user
to input any age so I will just write
STD C out and I want the user to input
any value so I will say please enter age
okay and then I will just end this line
and then I can check this age if this
age if this age is greater than so I
will just ask the user I will define our
variable int age is equal to 0 I will
initialize this age and then I will ask
the user to enter age so I will say STD
CIN for taking the input and then I will
take the input as an age right and if
this age is greater than 100 okay so I
am checking the condition if this age is
greater than for example 100 this is not
an human age I will consider this is my
condition to check any exception or this
age so I will say or or this age is less
than 0 then also this cannot be an age
so I can throw an exception so how you
throw an exception just use a keyword
throw and this is like throw and then
you throw a number or integer for
example through a 99 or 100
right - this is the username defined
integer I must say okay now if this
program throws you need to catch this in
the sketch block so what you can do you
can just define int as an argument of
catch int a and you can just print that
some exception occurred some extra
exception a code and you can give the
even the number of the exception okay so
how you can give the number of the
exception
you can just say error number is equal
to and then just give a here because we
have defined it he has an argument here
right now I'm just trying to compile and
I will just try to run the program and I
will see what it gives so I will enter
any age for example it's greater than
100 one zero nine and it gives an
exception some exception occurred an
exception number is 100 because we are
throwing 100 when the exception
condition occurs right in a similar way
I can throw any character also so for
example I want to show an character I
can just throw for example a as an
exception right and in here then I need
to define character as an argument and
then once again when I run the program
first I need to compile this and then I
will run this and this time I will enter
any - value minus 9 for example and it
gives me exception some exception occurs
error number is a this time because we
are tween
character this time right or you can use
a standard exception class from C++
which is used to you know handle any
exception standard exceptions we must
say so this you can use by using STD in
your catch a argument STD exception okay
and then you can catch the exception so
I will compile my program and this e
will give the error because this class
expect e dot there is a function member
function in exception class called what
to show the exception okay so I compiled
it and I run it and this time I will
enter 200 as an age and it gives me the
error that it's it has thrown an
exception okay so there is a library
called standard exception you can use to
catch the exceptions but for that I
almost forgot you need to include
exception library for that so you just
need to add this library called include
exceptions and this is for the C++
exception which is used to handle
exceptions right now for example you
don't know what kind of exception is
coming or you don't know the you know
type of exception which can occur in C++
so you can define multiple exception
handling for example in IE here or and
you can just use this catch multiple
times after your try block so this is my
triangle block this is
one kind of exception handling you can
do multiple kind of exception handling
like this so you can use care E or you
can even use undefined exception which
catches any exception and which is catch
with as an argument three dots and catch
as an and these three dot means that
it's you know any exception which occurs
can be cashed by this okay and always
remember this catch with three dots
always comes at the end of your try
catch exception block so you always
catch the known exception and then in
the in the case when the exception is
not known you use this so always add
this catch with these three blocks at
the end of your trying catch block okay
and I can run the program once again
it's showing an error which is okay
because I'm not using standard exception
P dot what is not required here and I
will compile my program and yeah because
there in this there is no exception
right we are not passing any any
argument here and I will run it once
again 1:22 I will catch the exception so
just notice that it has a cache which
exception so for example error number
exception occur messages like this or
error instead because we are catching
character here we can say error care ok
or here we can say unknown exception
unknown exception right and now when I
run the program compile it run run it
and for example I give any string value
and it handles this exception by coming
out of the block here and for example I
run this and I will give any character
and why it's not printing anything okay
I need to give the age first right yeah
thousand and it catches the exception
right like this now there are some
exception which you don't even know so
this is the user-defined the you know
throw some kind of some exception which
can occur at one time and you don't even
know which kind of exceptions are those
so you don't use throw in that case you
can just add this try and catch block
and if any exception occurs be those are
catch though by this so it's not
necessary that you will need to throw
the exception the C++ library will
handle your exceptions and catch if any
exception occurs using these cache block
also so in this way you can handle
exceptions in C++ I hope you have
enjoyed this video please rate comment
and subscribe and bye for now</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>