<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>JavaScript: Dirty Parts of the Language (aka Maneuvering JavaScript Errors) | Coder Coacher - Coaching Coders</title><meta content="JavaScript: Dirty Parts of the Language (aka Maneuvering JavaScript Errors) - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin, machine learning, AI, ML, tech talks, angular, javascript, js, typescript"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/Coding-Tech/">Coding Tech</a></li><li class="active">⤵</li></ol></div></div><h2 class="post__title"><b>JavaScript: Dirty Parts of the Language (aka Maneuvering JavaScript Errors)</b></h2><h5 class="post__date">2018-03-20</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/IcYRsNB3zD8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">my name is Brett little and I'm here to
talk to you about JavaScript and I'm not
here to talk to you about like the
exciting new framework or even the sexy
things about JavaScript I'm here to talk
to you about maybe the dirty parts of
the language which is why I call it the
bowels of JavaScript specifically error
handling in JavaScript whether you know
it or not
chances are right now in your
application your users are experiencing
errors and about a year ago a canapé and
I'm reeling a little bit of dirty
laundry to you here like this isn't the
exact graph but about a year ago we just
decided to start tracking errors in our
application as a percentage of unique
users so of all the users that use our
app on a day to day basis I wanted to
know what percentage of those users
unique users were actually seeing errors
me the optimistic type I thought it'd be
like one or two percent Mabley but you
know actually we're at we were averaging
around ten to fifteen percent and there
were some days up to thirty percent
which is absurd that's ridiculous thirty
percent of our users on a day saw some
sort of error so I want to encourage you
to get back to your office and find out
this metric if you don't know what this
metric is in your app it's something
that you should know because it's
affecting your users and if you don't
know about the error how are you ever
gonna fix it so how do you how do you
even figure this statistic out though
there's a number of tracking services
that are out there I'm not going to
spend a huge amount of time on these
some of them are free some of them are
cost some of them are self hosted some
of them are entirely hosted for you it
doesn't matter the main point is you
need something so now me your doctor I'm
coming to you here I'm asking you a
difficult question so who here uses an
error tracking service inside their app
okay so if there's nothing that you take
away from this talk nothing else go back
to your office it'll literally take you
five minutes to set up one of these
services inside your app and it will
make all the difference for your users
so start off though I really want I want
to talk a little bit about how do these
tracking services work so they work
through a variety of mechanisms inside
the browser but at the key he routed
them is window dot on error which is a
global callback that will get executed
whenever there is an error inside your
application specifically when this is
executed we have this message which
describes the error that happened the
file number or the file that the error
originated from well the line number and
then the column number column because if
you minify your code to five lines you
might have 10,000 columns then you we
also have an error object the error
object is really important actually all
of the other parameters are drivable
from the error object we'll talk about
that more in a bit this is this is
really how they work in their at their
core these error tracking services so
when we put this inside our app as you
would expect we saw a lot of these I bet
you've seen these inside your app to
cannot read property such and such of
undefined okay well I need to fix that
we also saw a lot of these and I had no
idea what this was failed to fetch okay
failed a fetch something something
didn't work thing as though there was no
stack trace with this
it just said failed to fetch I have no
idea why is it failing I've got no clue
okay well we also saw a lot of these
object object who's seen this before
okay well that's all it tells me it just
says object object it's a string no
stack trace no nothing and I'm like I'm
screwed
what is that and we didn't just have
like 5 or 10 of these we had like
thousands of these all right this is bad
this is really really bad
so let's talk a little bit about how
just error handling works in JavaScript
before we kind of dive into some of
those so this is really basic but we
have this function make error we execute
make error we're declaring an object and
there were accessing a property on that
object that is not defined we're gonna
get that first error everybody's seen
this before but the important thing to
realize is
cuz we're triggering an error that error
is gonna show up inside window dot own
error when it shows up inside window dot
on error we'll have a stack trace will
have an error message will be able to
debug that that's great right also in
JavaScript we can dynamically create
errors specifically here we're creating
this tricot bazolar error you do that by
saying new error you pass it a string of
some sort and then you throw it when you
throw that error and you create it it
also bubbles up and gets inside window
dot on error and then you can track that
you get a stack trace everything's good
you can actually find that error when
you want to now the question I have for
you is what happens when you throw a non
error object right here
we're throwing a string you could throw
an object literal you get through all
sorts of things the language doesn't
stop you who thinks this is good who
thinks this is bad who thinks this is
bad this is definitely bad why is this
bad it might be worth considering what
is an error object an error object is
when you say new error we create this
new tree Kobey's over error the error
object that's created has two properties
on it a message property in a stack
property the message property is
whatever you pass them to the
constructor happens to be the string
trippi's or but the stack property is a
magical property that is computed and
calculated that time you create the
error
not at the time it's thrown but at the
time you create the error and that is a
browser specific stack trace which is
specific to the browser and it helps you
find where the error is located so now
back to this question why is throwing a
string bad well it doesn't really do
anything special for us because now
inside window dot on error the error
parameter at the end ends up being a
string and because it's a string you
have no stack trace and once you have no
strap trace you have no way to actually
identify where this came from and even
if like your your library tries to use
some magic to throw a new error inside
here well the context that window dot an
error is executed in is on a new round
of the event loop and there is actually
no way for you to get a real stack trace
once you start throwing strings so never
throw strings always throw error objects
okay well when we have synchronous
errors we can wrap them in a try-catch
once we try catch an error we can have
some custom logic to handle the error
when that happens we're no longer
getting that error to bubble out inside
window it on air so we can actually like
swallow there okay you don't really
don't want to swallow errors but you can
have custom logic to handle it else
bubble it outside the catch statement
okay well what about asynchronous errors
so in this case we have a try-catch
around a set timeout a set timeout
executing a callback so we are never
gonna get inside this cap statement why
because this is asynchronous
set timeout make error make error being
the callback will never get execute well
it will never the error that its produce
will never be bubbled into this round of
the event loop it's getting executed not
a whole new round of the event loop so
it's not going to show up in the catch
statement at all but luckily enough this
error will show up inside window dot on
air so at least you can still debug it
but it's not going to show up inside the
catch statement what about promises
promises save us from asynchronous
things so we're calling make promise
which is this function which returns a
new promise inside there we're gonna
throw a new era of our Mikula as error
okay who thinks this is bad who likes
this code well the problem here is we
have no catch statement if you ever have
a promise and you have no catch
statement you're not bubbling that out
well guess what that error that's
created it could be you're calling a
function that's not defined accessing a
property of an undefined or a null
reference whatever error that you have
inside this promise if you have no catch
statement and you don't bubble that
promise reference out somewhere and have
somebody else catch it that will get
swallowed and you will never know about
this error the browser won't tell you
about it your error tracking service
won't tell you about it and you're
essentially screwed so if you're using
promises you need to make sure you have
a catch statement
okay well this previous slide I just
showed you we're just consul not
erroring the air but really we want to
log that so if we want to bubble this
out and get it into window dot on air
how about we throw inside the catch what
do you think it does this look good who
thinks this looks good no this is bad
you're gonna be worried about all my
questions now but uh so this is bad why
is this bad well promises themselves
chain and because promises chain the
catch statement itself produces a new
promise so if you're really gonna want
to get this error out of here you're
gonna need to have not then dot catch
and a whole nother dot catch statement
so like it chains and so now I'm like
how do I get this error outside of this
stupid little catch statement because I
want to make sure that it shows up
inside my bug tracking service well how
do I do that well I have a friend named
Jill Denning who once said all problems
are surmountable by a well-placed set
timeout and what do I mean by that we
can do this we can inside our cat
statement we can just say set timeout
throw error and because the set timeout
is executing this this callback on a new
round of the event loop it's gonna be
able to get bubble outside of that catch
and it's gonna show up inside window dot
on air which is really ugly this is like
crappy really crappy what else is wrong
with this code
well our trick of bizarre is back we're
throwing a non error object so remember
always throw error objects never throw
strings never ever throw strings or
object literals always throw error
objects okay let's look at a fetch an
example so the fetch API the fetch API
is a new API for making HTTP requests
that's native to the browser that
replaces Ajax okay we have this fetch
API we have this function run app run
app is going to call fetch data with a
bad ID when it calls fetch data with a
bad ID well we're gonna call the native
fetch API passing this bad ID to some
server and then we're gonna get inside
this dot then promise the response
object that comes inside here is native
to the browser it includes a dot okay
property
if the response from the server is a 200
level response dot okay we'll be truthy
I don't really care about that I care
about when it's false so in other words
we have a 400 500 level error from the
server
something happened wrong how do we how
do we create an error in a way that
makes this useful to debug later on well
given what we've talked about we could
throw a new error we could say error
treating data we could pass in the IDS
we could see maybe it's null or
undefined and then down here we can do
this really crappy like set timeout
throw error stuff you could do that a
couple of things I don't like yeah this
is weird that's really weird but then
also creating the errors right here has
some interesting effects remember I said
when you create an error object it
creates a stack from the point it was
created so because we are we are
creating the error object inside this
callback that means the stack Trace that
will be defined on that error will only
have that part of the stack it will not
have any of the rest of the stack a part
of it for example run app run app will
not be a part of the stack for this
error so if this code fetch data is used
all across your application like 10
different people call it you will never
know which one called that function
passing the bad ID and so that really
sure you're tracking this it's getting
to your error tracking service but
debugging this is going to be really
difficult to do so is there something we
could do to make this a little bit
easier well say we create the error
preemptively we maybe won't use it but
just in case we need it we can create it
preemptively and then if the response is
not okay we can mutate the error message
change it to whatever we want and then
we throw the error if you do that then
the error that comes out of here will
actually have the stack trace with run
app a part of it and then you know who
actually executed this and this isn't
necessarily something you always want to
do but this is like a tool in the tool
toolbox to realize that you can create
an error object whenever you want but
just because you created it doesn't mean
you
have to use it and then you can think
about when you're creating your error
object in a way that later on what I'm
trying to debug this I can make it more
useful so that I can actually figure out
what the problem is so again make sure
you get the stack right because that's
what's that's your best friend when
you're trying to debug the problem so
now I give you a more complex example
and take up just a minute or two to go
through this code so right here we have
a promise chain so we've gotten this
function run and inside run we're
calling make promise and inside make
promise we're calling make error and
make error we're just returning a
promise that is always going to reject
and throw an error a trick Oh bizarre
error once it comes up here we have our
dot then statement we're gonna change
the data or returning that promise it's
chaining up to here and then we're
dispatching the data and then we've got
this capture exception stuff which is an
easier way to do capturing the exception
to get to the server or our air tracking
service instead of doing our set timeout
stuff we instead we can use whatever
error tracking service directly use the
API to say catch the error that's what
we're doing there so the question I have
for everyone is does it matter where you
put your catch statement in a in a
promise chain so notice we have two dot
ends we have a dot then here and we have
a dot then there does it matter if the
catch statement is here there doesn't
matter if the catch statement is down
here who thinks the first one is like
the right way to do it the second one or
it doesn't even matter maybe you should
put it on both so let's walk through
this code and see if we can understand
what's going on and see what makes a
difference so let's start with the left
side so when we make the air it comes up
here there is no catch statement here
but because we're returning up the
promise out of here it chains and it
bubbles upward to here and there's a
catch statement there and so now the
error that was created down here will
show up inside our error tracking
service and will be
to find it and get it get it that works
that's fine let's look at it over here
though so now we make the air it bubbles
up to here and we have a catch name in
here and now we're also tricked getting
the air to our air tracking service so
they look equivalent looks like it
doesn't even really matter but now I
want you to consider what if there's an
error inside your dispatch code if
there's an error inside your dispatch
code say that the data that you got from
down here and it's being dispatched said
the data has a property that's not
defined and you're referencing it now
you're gonna get an error but because
you have no catch statement here you're
never gonna know about that error it's
gonna bust it's gonna break things it's
going to affect the user experience and
you're never gonna know about it and
it's not gonna show up on your tracking
service either so the lesson of this
story is you always want to at least
have your catch statements in a promise
chain at the highest level of the
promise chain you might want it in both
because you might want to be doing
something down here checking for some
specific type of error and then bubbling
it up if it's not that type of error and
handling it in some special way well
always you at least want it at the top
level of the chain because you don't
want to be excluding some of the code
from being getting caught from catching
bad errors that you don't expect so what
about async functions an error handling
async functions are a like almost like a
Guri way of dealing with asynchronous
code making it feel like synchronous
code so this example here we have a
simple sleep function that produces a
promise that will resolve after a set
amount of time well if you use this
keyword async on a function and when
it's executed so we're executing it down
here we're gonna come inside here and
every time it C it's the keyword await
and we invoke a function that produces a
promise it'll wait to proceed to the
next line until that that promise
resolves okay so it'll print one wait a
second print two wait a second and then
print three so how does this work with
errors though say our promise produces
an error a new trick Oh bizarre err
well the question I have for you is
what's gonna happen is this console dot
log statement going to print well no it
will not print and why will it not print
because remember async functions this
await says let's wait to proceed to the
next line until that promise resolves
but this promise never resolves and
because it never resolves it's never
going to proceed to the second line so
as with normal synchronous code with
async functions we can use try caches
and treat asynchronous code as if it was
synchronous and we can console dot error
our error right here well what if we
want to bubble this out to window dot on
air can we throw an error inside a catch
statement here and is that gonna bubble
out inside window dot on air well no it
will not
why because async functions themselves
produce promises and so essentially like
just because you have async function
here when you invoke that it will have a
dot catch statement it will also have a
dot then statement for whatever the
function finishes executing so if you're
ever executing a async function you
always want to have a dot catch
statement if you don't have a dot catch
statement you potentially have errors in
your app right now and you don't even
know about it because they're getting
swallowed
it's a big no-no right there so let's go
back to these let's go back to these so
the first one I think we've already kind
of discussed how these can come about
the second note one though failed the
fetch
what causes that well failed the fetch
we had some common code inside of our
app that was using the fetch API and so
everybody making a network request would
go through this common code well inside
this this common code with the fetch API
the case that I showed you about assumed
that we were always getting inside the
dot Venn statement well there's actually
a case where you never even get inside
dot Men you're just in dot catch and
when does that happen well that happens
when the server is not available
so say you're making a network request
to your server and it's completely down
it's not available at all then you're
gonna get a failed to fetch and we
discovered for our app that our rolling
deploys were not working quite right so
when we were deploying a new back-end
and we were trying to unload the the old
version of the back end and bring the
new one in there was a period of time
where there was no back end and so we
were getting failed the fetches it
wasn't very long but that period of time
was long enough to affect customers
rolling deploys were definitely down
that was bad
next problem is we had cores issues so
if you do not set the proper headers on
your cores responses you are never gonna
get inside this dot then statement
you're gonna immediately go to a dot
catch it doesn't matter if the server
returns a 200 a 400 or a 500 level
response if you don't have the right
headers on your response you're never
gonna get in here you're never gonna be
a little look at response not okay
you're never gonna look at the response
JSON or response data or response status
code you're just gonna immediately show
up inside
failed the fetch in the catch statement
so if you're seeing the inside your app
those are the two things I would look at
making sure rolling deploys are working
you have a back-end available and then
secondly if you're using cores is your
cores configured correctly and for us
this was disk difficult to debug because
it was only one of our back-end services
that had cores correctly in it
configured and only when they responded
the 401 did they not set course headers
so that was like a nightmare to figure
out that it was that API on a 401 that
was doing that so make sure that you're
setting cores properly across your app
under all circumstances under all
especially even error states so then we
also have this object object error and
for us this happened because we were
throwing non error objects specifically
we're throwing an object in this case
which is actually the response of whole
response object from the fetch API and
we figured hey we want this to show up
inside our tracking service we want all
the data a part of it let's just throw
the whole object but in reality the way
that throwing works is that's gonna be
to string into object object and that's
what shows up on my bug tracking service
is object object and it's just a string
and I have no way to track it I have no
way to figure out who caused it where it
came from what's going on and so the
lesson of this story is make sure you
always throw error objects so again
always throw error objects and promise
not reject error objects also make sure
that all of your promise chains have a
proper catch statement and when I say a
proper catch statement make sure that
your promise changes chains at least
have a catch statement at the highest
level of the promise chain maybe you can
have more riddled throughout the promise
chain but at least make sure there's one
at the top also make sure if you're ever
invoking in a syncing or asynchronous
function make sure that that invocation
also has a dot catch statement if you
don't have a dot catch statement you're
gonna be swallowing errors and you will
never know about it lastly code
defensively with debugging in mind and
this goes back to that example I gave
where I created the error preemptively
even though I might not use it so
specifically areas of your app the
boundary points of your app where you're
going to be communicating with another
system you can never guarantee that that
other system is going to respond with
correct data you always need to make
sure that you are handling
the edge case that that system is not
going to do what you expect it to do so
whenever you're making an AJAX request
make sure that you are handling the
error case and the way you handle the
error case make sure you do it in a way
that makes it easier for you to find it
six months from now if you just forget
about that error case it potentially is
going to be very very very hard to
figure it out and understand where that
rose later on so I also need to mention
a new API that is currently available in
chrome and nodejs so I mentioned
whenever you throw an error inside a
promise it gets completely swallowed yes
it does get completely swallowed and
there's a reason kind of why the
browser's implemented it that way and it
kind of relates to this code right here
so we have this promise where we are
creating we're rejecting this promise
with a new error well there is no catch
statement on this promise but we might
wait five seconds and catch that later
on it's really difficult for the browser
to know whether or not you're gonna
handle your error scenarios with your
promises and because it's really
difficult for them to know they just
assume that you know what you're doing
when in reality usually when I don't
have a catch statement it's because I
screwed up and I forgot to do it so
recently node and chrome have added this
new global event handler on unhandled
rejection and with on unhandled
rejection whenever you have a promise
that does not have a dot catch statement
on it immediately when the error is
created then this event is going to fire
and then you can essentially get a
warning about it and say whoo oh man
this might be a problem somewhere in my
code I am having a promise where I am
throwing an error and there is no catch
statement on that error which is very
very useful but again this is only
available in chrome I don't want to
emphasize this too much as like this
isn't available everywhere and so if you
are seeing these throughout your app go
fix them and go fix them because in edge
Internet Explorer Safari Firefox all
those other browsers you're not this is
not going to work for you so you need to
definitely make sure you're fixing those
promise errors
also there's that this other one on
rejection handled that gets fired when
you handle the rejection so when this
promise dot catch statement executes
that event handler will also fire so I
want to close with if your app throws
and there is no service there to track
it does it really make an error well yes
it does make an error because your users
are getting affected right now whether
you know it or not their experience is
worse because of the errors that we have
inside our apps and also if your promise
throws and there is no catch damn it
doesn't really make an error yes it does
even though it may be swallowed and even
though you may never know about it
your users know about it because your
user experience sucks when those errors
happen so thank you</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>